baseurl: ""
url: "https://wellsign.com"
title: "Wellsign"
destination: docs/

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

include: ["node_modules/tailwindcss"]

postcss:
  cache: false

exclude:
  - .gitignore
  - bin
  - package-lock.json
  - postcss.config.js
  - README.md

# Google Analytics
# google_analytics: UA-237212189-1
